name = "AUNO_MODULE"
description = "A Nadybot module to check comments on auno.org/aogalaxy.com"
version = "2.0.1"
author = "Nadyita"
github = "Nadybot/AUNO_MODULE"
bot_type = "Nadybot"
bot_version = "^7.0.0-alpha.1"
